export const polish =
	'się i w nie na z do to że a o jak ale po co tak za od go już jego jej czy przez tylko tego sobie jeszcze może ze kiedy pan ich dla by gdy teraz ja ten który nawet bardzo przed tu jednak pod coś tam wszystko przy więc nic bo nim żeby miał on być potem też jeśli bez nad gdzie lecz siebie nigdy ani właśnie sam u dobrze niż jakby aby ty oczy zawsze raz były no albo gdyby aż wtedy przecież ona drzwi jako chyba nagle wszyscy jeden czym kto sposób czas kilka dlaczego razem jutro';

export const english =
	'the be of and a to in he have it that for they I with as not on she at by this we you do but from or which one would all will there say who make when can more if no man out other so what time up go about than into could state only new year some take come these know see use get like then first any work now may such give over think most even find day also after way many must look before great back through long where much should well people down own just because good each those feel seem how high too place little world very still nation hand old life tell write become here show house both between need mean call develop under last right move thing general school never same another begin while number part turn real leave might want point form off child few small since against ask late home interest large person end open public follow during present without again hold govern around possible head consider word program problem however lead system set order eye plan run keep face fact group play stand increase early course change help line';

export const german =
	'ja wurde jetzt immer seinen wohl dieses ihren würde diesensondern weil welcher nichts diesem alles waren will Herr vielmein also soll worden lassen dies machen ihrer weiter Lebenrecht etwas keine seinem ob dir allen großen Jahre Weisemüssen welches wäre erst einmal Mann hätte zwei dich alleinHerren während Paragraph anders Liebe kein damit gar Hand Herrneuch sollte konnte ersten deren zwischen wollen denen dessen sagenbin Menschen gut darauf wurden weiß gewesen Seite bald weitgroße solche hatten eben andern beiden macht sehen ganze anderenlange wer ihrem zwar gemacht dort kommen Welt heute Frauwerde derselben ganzen deutschen lässt vielleicht meiner';

export let french =
	'maison tête ville temps porte pays route raison homme cœur femme dieu amour monde voiture jour temps monsieur bien personne fois part rue chambre monde être voir avoir demander pouvoir trouver faire rendre mettre venir dire passer devoir comprendre prendre rester donner tenir aller porter vouloir parler savoir montrer lent fort rapide magnifique méchant merveilleux belle brave intelligent Dynamique ancien élégant nouveau énervé triste Sombre heureux Mauvais Adorable Possible Timide Moyen bon Fatigant Rapidement presque Malheureusement bientôt Lentement cependant Couramment désormais Egalement davantage Parfois Vraiment encore habituellement tellement régulièrement certainement calmement probablement tranquillement précisément jamais beaucoup partout souvent';
